[bin]
name = "BIN"
desc = "Basic Instruction Name"
more = "Used as a macro to reference the YARV instruction. Converts pop into YARVINSN_pop"

[bop]
name = "bop"
desc = "Basic Operator"
more = "Relates to methods like Integer plus and minus which can be optimized as long as they haven't been redefined"
