[cc]
name = "cc"
desc = "Call Cache"
more = "An inline cache structure for the call site. Stored in the 'cd'"
see = 'cd'

[ci]
name = "ci"
desc = "Call Information"
more = "Refers to an rb_callinfo struct. Contains call information about the call site, including number of parameters to be passed, whether it they are keyword arguments or not, etc. Used in conjunction with the 'cc' and 'cd'"
see = ['cc', 'cd']

[cd]
name = "cd"
desc = "Call Data"
more = "A data structure that points at the 'ci' and the 'cc'. 'iseq' objects points at the 'cd', and access call information and call caches via this structure"
see = ['ci', 'cc']

[cfp]
name = "cfp"
desc = "Control Frame Pointer"
more = "Represents a Ruby stack frame. Calling a method pushes a new frame (cfp), returning pops a frame. Points at the 'pc', 'sp', 'ep', and the corresponding 'iseq'"
see = ['pc', 'sp', 'ep', 'iseq']

[cvar]
name = "cvar"
desc = "Class Variable"
more = "Refers to a Ruby class variable like @@foo"
see = 'ivar'
