[iseq]
name = "iseq"
desc = "Instruction Sequence"
more = "Usually 'iseq' in the C code will refer to an 'rb_iseq_t' object that holds a reference to the actual instruction sequences which are executed by the VM. The object also holds information about the code, like the method name associated with the code."
